name: Publish to npm

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for MinVer to work correctly
          filter: tree:0 # Treeless clone for better performance

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      # Use MinVer to determine the version
      - name: Determine Version
        id: minver
        uses: thefringeninja/action-minver@2.0.0-preview1
        with:
          # Start with version 1.0.0
          minimum-major-minor: 1.0 # Start with 1.0.x
          tag-prefix: v # Use 'v' prefix for version tags
          default-pre-release-phase: '' # No pre-release phase

      # Update package.json version with the version from MinVer
      - name: Update package.json version
        run: |
          npm version ${{ steps.minver.outputs.version }} --no-git-tag-version

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build the project
      - name: Build
        run: npm run build

      # Make the build/index.js file executable
      - name: Make executable
        run: chmod +x ./build/index.js

      # Publish to npm
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
